import { countries } from '../helpers'

export default (render, values) => {
    const defaults = {
        field: 'value',
        headerName: 'Value',
    }

    switch(values.type){
        case 'Blogging':
            return render('ENUM', {
                ...defaults,
                options: [
                    "All Blogging",
                    "Ameba",
                    "Blogger",
                    "Destructoid",
                    "FC2",
                    "Jimdo",
                    "Sina Weibo",
                    "Tianya",
                    "TypePad",
                    "WordPress"
                ]
            })
        case 'Email':
            return render('ENUM', {
                ...defaults,
                options: [
                    "All Email",
                    "Aweber",
                    "bmpp",
                    "Eudora Set",
                    "Gmail",
                    "GMX Mail",
                    "Groupwise",
                    "Host-based email (POP3/IMAP/SMTP)",
                    "Hotmail",
                    "Interactive Mail Support Protocol",
                    "Internet Message Access Protocol over TLS/SSL",
                    "Internet Message Access Protocol version 4",
                    "Mail Submission Agent",
                    "Mail.ru",
                    "MailChimp",
                    "MAILQ",
                    "Messaging Application Programming Interface",
                    "Microsoft Exchange",
                    "MS Exchange Routing",
                    "Netix Message Posting Protocol",
                    "NI MAIL",
                    "On-Demand Mail Relay",
                    "Post Office Protocol - Version 2",
                    "Post Office Protocol 3",
                    "Post Office Protocol 3 over TLS",
                    "Quick Mail Queuing Protocol",
                    "Quick Mail Transfer Protocol",
                    "Rackspace Hosted Exchange",
                    "Remote Mail Checking Protocol",
                    "Secure Simple Mail Transfer Protocol",
                    "SEND",
                    "Simple Mail Transfer Protocol",
                    "Web based email",
                    "Windows Live Hotmail and Outlook",
                    "XNS mail",
                    "Yahoo Mail"
                ]
            })
        case 'File sharing':
            return render('ENUM', {
                ...defaults,
                options: [
                    "All File sharing",
                    "Apple file sharing",
                    "Box",
                    "Dropbox",
                    "File Transfer [Default Data]",
                    "Financial Information eXchange",
                    "ftp protocol  control  over TLS/SSL",
                    "Globus GridFTP",
                    "Google Talk File Transfer",
                    "Grid FTP",
                    "Hangouts File Transfer",
                    "Mega",
                    "Microsoft OneDrive",
                    "Microsoft-DS",
                    "Multisource File Transfer Protocol",
                    "NetApp SnapMirror",
                    "Network File System",
                    "NI FTP",
                    "OSCAR File Transfer",
                    "PFTP",
                    "Prospero Directory Service",
                    "PutLocker.com",
                    "RemoteFS",
                    "rsync",
                    "SCSI on ST",
                    "Secure FTP Data",
                    "Sender-Initiated/Unsolicited File Transfer",
                    "Simple Asynchronous File Transfer",
                    "Simple File Transfer Protocol",
                    "Softros LAN Messenger and File Transfer",
                    "Trivial File Transfer Protocol",
                    "TusFiles",
                    "UUCP Path Service",
                    "Windows file sharing"
                ]
            })
        case 'Gaming':
            return render('ENUM', {
                ...defaults,
                options: [
                    "All Gaming",
                    "Battle.net",
                    "Big Fish Games",
                    "Blizzard",
                    "BNet",
                    "Call of Duty",
                    "DirectPlay",
                    "DirectPlay8",
                    "DOOM",
                    "Game-spy Online Gaming",
                    "GameSpot",
                    "GREE",
                    "IGN",
                    "IPX network emulator for DOS and Windows",
                    "Maplestory",
                    "Miniclip",
                    "Parsec Gameserver",
                    "PlayStation",
                    "Playstation Store",
                    "pogo.com",
                    "QQ-Games",
                    "Secondlife",
                    "Steam",
                    "TeamSound",
                    "World of Warcraft",
                    "Xbox LIVE",
                    "Xfire Instant Messaging Service",
                    "Zynga"
                ]
            })
        case 'News':
            return render('ENUM', {
                ...defaults,
                options: [
                    "All News",
                    "ABC News",
                    "BBC",
                    "Business Insider",
                    "BuzzFeed",
                    "CBS",
                    "CNBC",
                    "CNET",
                    "CNN",
                    "Daily Mail",
                    "Drudge Report",
                    "E! Online",
                    "Feedly",
                    "Fox News",
                    "Gizmodo",
                    "Indiatimes",
                    "MSN",
                    "NBC News",
                    "New York Times",
                    "NY Daily News",
                    "Patch.com",
                    "People.com",
                    "Rediff.com",
                    "Reuters",
                    "SFGate",
                    "sina.com.cn",
                    "Sky.com",
                    "TechCrunch",
                    "The Atlantic",
                    "The Blaze",
                    "The Daily Beast",
                    "The Hollywood Reporter",
                    "The Huffington Post",
                    "The Telegraph",
                    "The Washington Post",
                    "The Xinhuanet",
                    "TMZ",
                    "turner.com",
                    "UOL",
                    "USA Today",
                    "Wall Street Journal"
                ]
            })
        case 'Online backup':
            return render('ENUM', {
                ...defaults,
                options: [
                    "All Online backup",
                    "Backblaze",
                    "Backup service",
                    "Carbonite",
                    "Connected Backup",
                    "Crashplan",
                    "IBackup",
                    "iCloud",
                    "Mozy",
                    "NovaStor Backup",
                    "Tobit David Replica",
                    "Yosemite Tech Tapeware"
                ]
            })
        case 'Peer-to-peer (P2P)':
            return render('ENUM', {
                ...defaults,
                options: [
                    "All Peer-to-peer (P2P)",
                    "Ares",
                    "BitTorrent",
                    "BitTorrent Networking",
                    "DC++",
                    "Distributed Hash Table",
                    "eDonkey",
                    "eDonkey Static",
                    "Encrypted Bittorrent",
                    "Encrypted eMule (eDonkey and Kademlia)",
                    "FastTrack",
                    "Filetopia",
                    "Gnutella",
                    "GoBoogy",
                    "Kazaa",
                    "Konspire2b",
                    "Manolito",
                    "networking-gnutella",
                    "Pando",
                    "Perfect Dark",
                    "poco",
                    "Share",
                    "Soulseek",
                    "Tomatopang",
                    "Waste",
                    "Webthunder",
                    "WinMX",
                    "Winny",
                    "xunlei"
                ]
            })
        case 'Social web & photo sharing':
            return render('ENUM', {
                ...defaults,
                options: [
                    "All Social web & photo sharing",
                    "Badoo",
                    "Douban",
                    "Facebook",
                    "Facebook Audio Streaming",
                    "Facebook Media Streaming",
                    "Facebook Video Streaming",
                    "Flickr",
                    "Google Talk",
                    "Google Talk Chat",
                    "Hangouts",
                    "Hangouts Audio",
                    "Hangouts Chat",
                    "HootSuite",
                    "ICQ",
                    "ImageShack",
                    "img.ly",
                    "imgur.com",
                    "Instagram",
                    "IP Messenger",
                    "Jabber",
                    "Kakao-Services",
                    "Kakao-Talk",
                    "Line",
                    "Mashable",
                    "Mixi",
                    "MySpace",
                    "photobucket.com",
                    "Picasa",
                    "Pinterest",
                    "QQ Instant Messenger",
                    "Shutterstock",
                    "smugmug",
                    "Snapchat",
                    "Tagged",
                    "Taringa",
                    "theCHIVE",
                    "twitpic",
                    "Twitter",
                    "VKontakte",
                    "WeChat",
                    "WhatsApp",
                    "Yahoo Messenger",
                    "Yelp",
                    "yfrog"
                ]
            })
        case 'Sports':
            return render('ENUM', {
                ...defaults,
                options: [
                    "All Sports",
                    "Bleacher Report",
                    "CBS Sports",
                    "ESPN",
                    "ESPN video streaming",
                    "foxsports.com",
                    "mlb.com",
                    "nhl.com",
                    "Nike"
                ]
            })
        case 'Video & music':
            return render('ENUM', {
                ...defaults,
                options: [
                    "All Video & music",
                    "AirPlay",
                    "Apple QuickTime",
                    "BBC iPlayer",
                    "blip.tv",
                    "BrightTalk",
                    "Dailymotion",
                    "DirecTV Data Catalog",
                    "DirecTV Webcasting",
                    "Disney",
                    "Flash Video",
                    "Flash Yahoo",
                    "Food Network",
                    "grooveshark.com",
                    "Gyao",
                    "HBO GO",
                    "hulu.com",
                    "iTunes",
                    "iTunes Media",
                    "iTunes-audio",
                    "iTunes-video",
                    "KeyHoleTV",
                    "Kuro",
                    "last.fm",
                    "LeTV",
                    "LiveStation",
                    "megavideo.com",
                    "Microsoft Stream",
                    "Miscellaneous audio",
                    "Miscellaneous video",
                    "MPEG-2 Transport Stream",
                    "MTV",
                    "Napster",
                    "Netflix",
                    "Niconico",
                    "Pandora",
                    "PPstream",
                    "PPTV",
                    "Public Broadcasting Service",
                    "QQLive",
                    "rdio.com",
                    "Real Data Transport",
                    "Real Time Messaging Protocol Encrypted",
                    "Real Time Messaging Protocol Tunneled",
                    "RealMedia Traffic",
                    "Rhapsody",
                    "Sling",
                    "SopCast",
                    "Soribada",
                    "soundcloud.com",
                    "Spotify",
                    "TED",
                    "Tudou",
                    "TwitchTV",
                    "ustream.tv",
                    "Vimeo",
                    "Xfinity TV",
                    "Xunlei Kankan",
                    "Youku",
                    "YouTube",
                    "Zattoo"
                ]
            })
        case 'VoIP & video conferencing':
            return render('ENUM', {
                ...defaults,
                options: [
                    "All VoIP & video conferencing",
                    "Audio Over HTTP",
                    "Cisco Collaboration Audio",
                    "Cisco Collaboration Control",
                    "Cisco Collaboration Media",
                    "Cisco Collaboration Video",
                    "Cisco Digital Media Player",
                    "Cisco IP Camera",
                    "Cisco IP SLA",
                    "Cisco Jabber Audio",
                    "Cisco Jabber Control",
                    "Cisco Jabber IM",
                    "Cisco Jabber Video",
                    "Cisco Media Audio",
                    "Cisco Media Video",
                    "Cisco NAC",
                    "Cisco Phone",
                    "Cisco Phone Audio",
                    "Cisco Phone Control",
                    "Cisco Phone Media",
                    "Cisco Phone Video",
                    "cisco smart probe",
                    "Cisco Spark",
                    "Cisco Spark Audio",
                    "Cisco Spark Media",
                    "Cisco Spark Video",
                    "Cisco TV",
                    "Conferencing",
                    "Conferencing Server",
                    "CRYPTOAdmin",
                    "Dropcam",
                    "Entrust Key Management Service Handler",
                    "Facetime",
                    "Google Services Audio",
                    "Google Services Media",
                    "Google Services Video",
                    "Google Talk Video",
                    "Google Talk Voice",
                    "GoToMeeting",
                    "H.225",
                    "H.245",
                    "H.323",
                    "Hangouts Media",
                    "Hangouts Video",
                    "Inter-Asterisk eXchange",
                    "Internet Security Association and Key Management Protocol",
                    "Internet video conference system",
                    "Jabber Audio",
                    "Jabber Video",
                    "Jive Software",
                    "Lifesize",
                    "Media Gateway Control Protocol",
                    "Microsoft Teams",
                    "MS Teams App Sharing",
                    "MS Teams Audio",
                    "MS Teams Media",
                    "MS Teams Video",
                    "Philips Video-Conferencing",
                    "Real-Time Transport Control Protocol",
                    "Real-time Transport Protocol",
                    "Real-time Transport Protocol Audio",
                    "Real-time Transport Protocol Video",
                    "RingCentral",
                    "Ringcentral Audio",
                    "Ringcentral Control",
                    "Ringcentral Media",
                    "Ringcentral Video",
                    "RTSPS",
                    "SCCP (Skinny Call Control Protocol)",
                    "Secure Data Network System Key Management Protocol",
                    "Secure SIP",
                    "SIP (Voice)",
                    "Skype",
                    "Skype for Business (MS-Lync)",
                    "Skype for Business (MS-Lync) Audio",
                    "Skype for Business (MS-Lync) Control",
                    "Skype for Business (MS-Lync) Video",
                    "Teamspeak",
                    "Telepresence Audio",
                    "Telepresence Control",
                    "Telepresence Media",
                    "Ventrilo",
                    "Viber",
                    "Video Over HTTP",
                    "Vocera",
                    "Web conferencing solution for web meetings",
                    "WebEx",
                    "Webex Application Sharing",
                    "Webex Audio",
                    "WebEx Control",
                    "WebEx Meeting",
                    "Webex Video",
                    "WebRTC",
                    "WebRTC Audio",
                    "WebRTC Video",
                    "Wi-Fi Calling",
                    "Yahoo Messenger Video",
                    "Yahoo VoIP Messenger",
                    "Yahoo VoIP over SIP",
                    "Zoom Meetings"
                ]
            })
        case 'Web file sharing':
            return render('ENUM', {
                ...defaults,
                options: [
                    "All Web file sharing",
                    "4shared.com",
                    "Binary over HTTP",
                    "download.com",
                    "Easynews",
                    "easyshare.com",
                    "filefactory.com",
                    "filefront.com",
                    "filer.com",
                    "filestube.com",
                    "gigeshare.com",
                    "hotfile.com",
                    "massmirror.com",
                    "mediafire.com",
                    "megashare.com",
                    "megaupload.com",
                    "RapidShare",
                    "rapidshare.com",
                    "SourceForge",
                    "thepiratebay.org",
                    "torrentz.com",
                    "ultrashare.de",
                    "upload.com",
                    "WeTransfer",
                    "Zippyshare",
                    "zshare.net"
                ]
            })
        case 'Software & anti-virus updates':
            return render('ENUM', {
                ...defaults,
                options: [
                    "All Software & anti-virus updates",
                    "adobe updates",
                    "Android Updates",
                    "Antivirus updates",
                    "Apple App Store",
                    "Apple iOS updates",
                    "Apple Updates",
                    "AppleTV updates",
                    "bitdefender",
                    "eset",
                    "Google Downloads Services",
                    "Google Play",
                    "Java Update",
                    "kaspersky",
                    "MAC OS X updates",
                    "Microsoft Windows Store",
                    "Microsoft Windows Update Service",
                    "Software updates",
                    "sophos",
                    "symantec",
                    "webrootcloudav.com"
                ]
            })
        case 'Security':
            return render('ENUM', {
                ...defaults,
                options: [
                    "All Security",
                    "avast",
                    "Cisco Cognitive Threat Analytics",
                    "Cisco Stealthwatch",
                    "cisco umbrella",
                    "DigiCert",
                    "McAfee Antivirus"
                ]
            })
        case 'Productivity':
            return render('ENUM', {
                ...defaults,
                options: [
                    "All Productivity",
                    "Active Directory",
                    "ActiveSync",
                    "Adobe Creative Cloud",
                    "Amazon EC2",
                    "Atlassian",
                    "Automatic Data Processing",
                    "Bitbucket",
                    "Cisco SD-WAN IPSec",
                    "Computer Resources Sharing Application",
                    "Control And Provisioning of Wireless Access Points Data Protocol",
                    "Coursera",
                    "DameWare Mini Remote Control",
                    "Demandware",
                    "Distributed Compiler",
                    "GitHub",
                    "iPass",
                    "Jira",
                    "mDNS",
                    "Microsoft Office Web Applications",
                    "Microsoft Windows Live Services Authentication",
                    "Mikogo",
                    "MindTouch",
                    "Office 365",
                    "OpenVPN",
                    "Oracle",
                    "Oracle E-Business Suite - Un-encrypted Traffic",
                    "PDL data streaming port",
                    "Pearson Education",
                    "Perforce",
                    "Pocket",
                    "Prezi",
                    "Rational ClearCase",
                    "remote access and desktop sharing",
                    "Remote Desktop Protocol",
                    "SAP",
                    "Sharepoint",
                    "Siebel CRM",
                    "Simphony.NET",
                    "Siri",
                    "Slack",
                    "Slack Media",
                    "Stack Overflow",
                    "Timbaktu Remote Control Software",
                    "Virtual Network Computing",
                    "Vmware Vmotion",
                    "VNC over HTTP",
                    "Windows Live Office",
                    "X-Windows Remote Access",
                    "Zendesk",
                    "Zoho Services"
                ]
            })
        case 'Remote monitoring & management':
            return render('ENUM', {
                ...defaults,
                options: [
                    "All Remote monitoring & management",
                    "Apple Remote Desktop",
                    "auvik",
                    "Citrix Audio",
                    "Citrix ICA",
                    "Citrix Online",
                    "Citrix Static",
                    "GotoDevice",
                    "Gotomypc",
                    "LogMeIn",
                    "Marconet",
                    "MyRMM",
                    "PCoIP",
                    "Remote Admin",
                    "Remote desktop",
                    "Sflow Traffic Monitoring",
                    "showmypc",
                    "Vmware View"
                ]
            })
        case 'Business management':
            return render('ENUM', {
                ...defaults,
                options: [
                    "All Business management",
                    "Concur",
                    "Deltek Axium",
                    "IFS",
                    "Intacct",
                    "IQMS",
                    "Microsoft Dynamics 365",
                    "NetSuite",
                    "Priority ERP",
                    "salesforce.com",
                    "SICOM Restaurant Management",
                    "SugarCRM",
                    "Workday"
                ]
            })
        case 'Health care':
            return render('ENUM', {
                ...defaults,
                options: [
                    "All Health care",
                    "Allscripts",
                    "Cerner",
                    "CureMD",
                    "Digital Imaging and Communications in Medicine",
                    "Epic EHR",
                    "GE Healthcare",
                    "Health Level 7",
                    "McKesson"
                ]
            })
        case 'Web payments':
            return render('ENUM', {
                ...defaults,
                options: [
                    "All Web payments",
                    "Apple Pay",
                    "Bitcoin",
                    "Intuit",
                    "Lightspeed Retail POS",
                    "LivePOS",
                    "Mondex",
                    "PayPal",
                    "PayU",
                    "ShopKeep",
                    "Square",
                    "Stripe"
                ]
            })
        case 'Databases & cloud services':
            return render('ENUM', {
                ...defaults,
                options: [
                    "All Databases & cloud services",
                    "Amazon Cloudfront",
                    "Amazon RDS",
                    "Amazon Redshift",
                    "Amazon S3",
                    "Amazon Web Services",
                    "Azure",
                    "Cassandra",
                    "DB service",
                    "dBase",
                    "DDM Distributed File management",
                    "DDM-Remote Relational Database Access",
                    "Domino Domain Monitor database - Remote DB Access Using Secure Sockets",
                    "GDS DataBase",
                    "IBM Cloud",
                    "IBM Informix SQL Interface",
                    "IBM-DB2",
                    "Ingres/Net",
                    "Microsoft OLAP",
                    "Microsoft SQL Monitor",
                    "Microsoft SQL Server",
                    "mongo",
                    "mySQL",
                    "oracle",
                    "Oracle Business Intelligence",
                    "Oracle coauthor",
                    "Oracle Names",
                    "Oracle Net8 Cman",
                    "Oracle Net8 CMan Admin",
                    "Oracle Remote Data Base",
                    "Oracle TCP/IP Listener",
                    "Plus Fives MUMPS",
                    "postgresql",
                    "REAL SQL Server",
                    "Remote Database Access",
                    "SAP Cloud Platform",
                    "SAP Hana",
                    "SQL Service",
                    "SQL*NET",
                    "SQL-NET",
                    "Sqli",
                    "Sybase",
                    "VVPS-Qua",
                    "Z39.50"
                ]
            })
        case 'Advertising':
            return render('ENUM', {
                ...defaults,
                options: [
                    "All Advertising",
                    "Adcash",
                    "Advertising.com",
                    "AppNexus",
                    "Backpage.com",
                    "Brightroll",
                    "DoubleVerify",
                    "Google advertising",
                    "Integral Ad Science",
                    "LKQD",
                    "moatads",
                    "mopub",
                    "OpenX",
                    "Outbrain",
                    "Pubmatic",
                    "SpringServe"
                ]
            })
        case 'Countries':
            return render('ENUM', {
                ...defaults,
                options: countries,
                multiple: true,
                value: values.value?.length ? values?.value?.split(', ') : [],
                onChange: (newValues, currentValues, handleChange) => {
                    handleChange(newValues.sort().join(', '))
                }
            })
        default:
            return render('STRING')
    }
}