image:
  name: docker/compose:latest
services:
  - docker:dind

stages:
  - lint
  - test

before_script:
  - echo "Starting CI/CD Pipeline..."

lint_python:
  stage: lint
  image: python:3.11.7
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - pip install flake8
    - flake8 --config=backend/app/.flake8 backend/app/
    - echo "Linting Test Completed Sucessfully"

test_backend:
  stage: test
  script:
    - echo "Installing openssl..."
    - apk update
    - apk add openssl
    - echo "********* openssl installed sucessfully ******** "
    - echo "Encrypting ENV file"
    - openssl enc -d -aes-256-cbc -in .env.enc -out .env.dev -k "$ENCRYPTION_PASSPHRASE" -pbkdf2
    - echo "decryption SucessFULL."
    - echo "Running tests..."
    - docker-compose -f docker-compose.dev.yml run fast_api pytest -p no:warnings tests
    - echo "Test Completed Sucessfully."
  
after_script:
  - echo "CI/CD Pipeline finished."
